---
- name: restart postfix
  service: name=postfix state=restarted

- name: reload postfix
  service: name=postfix state=reloaded

- name: postmap generic
  shell: postmap /etc/postfix/generic

- name: postmap relayhost_map
  shell: postmap /etc/postfix/relayhost_map

- name: postmap sasl_passwd
  shell: postmap /etc/postfix/sasl_passwd

- name: postmap sasl_passwd_02
  shell: postmap /etc/postfix/sasl_passwd_02


